export type {
  AssumptionSetId,
  BaseSalary,
  BenefitCertainty,
  BenefitLabel,
  CalculationContext,
  CalculationYear,
  CareInsuranceChildStatus,
  ChurchTaxStatus,
  ComparisonBenefit,
  ComparisonInput,
  CompensationGuarantee,
  CompensationInput,
  CoupleScenarioInput,
  Currency,
  DecimalString,
  EmploymentCategory,
  EmployerContributionInput,
  EuroAmount,
  ExplicitUnknown,
  FederalStateCode,
  HealthInsuranceInput,
  IndividualSalaryScenarioInput,
  IsoDate,
  Locale,
  OfferComparisonInput,
  OneOffPayment,
  PayPeriod,
  PayrollCountry,
  PercentageRate,
  PrivateHealthInsuranceInput,
  RegistryOptionId,
  RegularAdditionalCash,
  ResolvedScenarioMetadata,
  SalaryAlternativeInput,
  SalaryAlternativeOverrides,
  ScenarioLabel,
  ScopeAdmissionInput,
  SemverString,
  SocialInsuranceInput,
  SpecialEmploymentCase,
  StatutoryHealthInsuranceInput,
  UnknownHealthInsuranceInput,
  WageTaxInput,
} from './types'

export { validateIndividualSalaryScenario } from './validation'
export {
  ExactDecimal,
  addDecimals,
  addEuroCents,
  compareDecimals,
  decimal,
  divideDecimals,
  euroAmountToCents,
  euroCentsToAmount,
  formatEuroCents,
  fromEuroCents,
  multiplyByPercentage,
  multiplyCentsByPercentage,
  multiplyDecimals,
  percentToRatio,
  quantizeDecimal,
  subtractDecimals,
  subtractEuroCents,
  sumEuroCents,
  toEuroCents,
} from './precision'
export type { CentConversionMode, EuroCents, RoundingMode } from './precision'
export type {
  LocalizedValidationMessage,
  SalaryValidationIssue,
  SalaryValidationResult,
  SalaryValidationRules,
  ValidationIssueCode,
} from './validation'
