export type {
  AssumptionSetId,
  BaseSalary,
  BenefitCertainty,
  BenefitLabel,
  CalculationContext,
  CalculationYear,
  CareInsuranceChildStatus,
  ChurchTaxStatus,
  ComparisonBenefit,
  ComparisonInput,
  CompensationGuarantee,
  CompensationInput,
  CoupleScenarioInput,
  Currency,
  DecimalString,
  EmploymentCategory,
  EmployerContributionInput,
  EuroAmount,
  ExplicitUnknown,
  FederalStateCode,
  HealthInsuranceInput,
  IndividualSalaryScenarioInput,
  IsoDate,
  Locale,
  OfferComparisonInput,
  OneOffPayment,
  PayPeriod,
  PayrollCountry,
  PercentageRate,
  PrivateHealthInsuranceInput,
  RegistryOptionId,
  RegularAdditionalCash,
  ResolvedScenarioMetadata,
  SalaryAlternativeInput,
  SalaryAlternativeOverrides,
  ScenarioLabel,
  ScopeAdmissionInput,
  SemverString,
  SocialInsuranceInput,
  SpecialEmploymentCase,
  StatutoryHealthInsuranceInput,
  UnknownHealthInsuranceInput,
  WageTaxInput,
} from './types'

export { validateIndividualSalaryScenario } from './validation'
export type {
  LocalizedValidationMessage,
  SalaryValidationIssue,
  SalaryValidationResult,
  SalaryValidationRules,
  ValidationIssueCode,
} from './validation'
